# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env:
           - BUILD_NAME=trusty_release
           - DETAILS="trusty release build"

# set NOT_CRAN to true to ensure that skip_on_cran tests are run here
env:
  - NOT_CRAN=true
  - _R_CHECK_FORCE_SUGGESTS_=false # to avoid failure because of aadcdb suggest

after_success:
  - Rscript -e 'covr::codecov()'

