---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# sohungry

Overview
--------

This R package provides access to the SCAR Southern Ocean Diet and Energetics Database: see http://data.aad.gov.au/trophic/.


Installing
----------

```{r, eval=FALSE}
install.packages("devtools")
library(devtools)
install_github("SCAR/sohungry")
```

Usage
-----

```{r, message=FALSE, warning=FALSE}
library(sohungry)
library(dplyr)
```

Load the desired dataset using `so_isotopes()` or `so_diet()`. Note that these read the data from the server (or cache, depending on caching settings). For fastest performance should probably be called once per session and kept in memory:
```{r, message=FALSE}
x <- so_isotopes()
```

Filter the data:
```{r, message=FALSE}
x %>% filter(taxon_name=="Electrona carlsbergi") %>% select(delta_13c_mean,delta_15n_mean)
```
